### ISSUE TITLE
Wallet not responsive, very slow each time it is clicked

### ISSUE THREAD

**Issue by fredfalcon** [coinonat/CoinonatX#7]
version 2.0.2.2 - on Windows. Anytime I click the app it freezes and becomes unresponsive for 10 seconds or so.

**Comment by normtomlins** [comment]
I am also having the same issues, it makes it almost impossible to do anything.   Running under Windows 10.

**Comment by fredfalcon** [comment]
@normtomlins I suggest stopping the app, click cancel so it closes, then restart it and do everything fast within the first 10-20 seconds.  It will then slow down every time and you can restart it and then perform the actions fast again.  This method helped me.

**Comment by coinonat** [comment]
Problem fixed in new wallet version.

**Comment by LithMage** [comment]
this issue still not fixed, every 15-30s (didnt time it) it hogs 100% CPU and becomes  Not responding for ~5-10s (On windows server 2012).

**Comment by BraamSteyn7777** [comment]
Hi
Wallet is not syncing. Impossible to do anything. Running under Windows 10
Running V2.0.2.2: MN-Swap-Ready

**Comment by dnovacik** [comment]
Can confirm, on win server 2012 it still gets unresponsive.

**Comment by tucksmcgucks** [comment]
Perhaps an issue with your Visual C++, try reinstalling from Microsoft's
website:

https://my.visualstudio.com/Downloads?pid=2082

- Tucker

**Comment by unsub23** [comment]
Wallet seems to still have the same problem. Setting up masternode, and wallet shows 0 on the network. wont sync.

**Comment by deflabs** [comment]
I'm using CoinonatX version 2.0.3.3 - 60022
At the bottom of the window, it says syncing with network... and next to that, it  says  "23 weeks behind".
Has anyone esle seen this?
